modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "GPL-3.0"

[[mods]]
modId = "dainty"
version = "1.0.0"
displayName = "Dainty"
authors = "Violet"
description = '''Adds a bunch of quality-of-life changes to Minecraft.'''

[[mixins]]
config = "dainty.mixins.json"

[[dependencies.dainty]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.dainty]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
